
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Jul 25 18:55:30 CEST 2024
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym_old{
  /* terminals */
	public static final int EOF = 0;
	public static final int error = 1;
	public static final int PROGRAM = 2;
	public static final int NAMESPACE = 3;
	public static final int LBRACE = 4;
	public static final int RBRACE = 5;
	public static final int CONST = 6;
	public static final int EQUAL = 7;
	public static final int SEMI = 8;
	public static final int COMMA = 9;
	public static final int LSQUARE = 10;
	public static final int RSQUARE = 11;
	public static final int STATIC = 12;
	public static final int COLON = 13;
	public static final int IF = 14;
	public static final int ELSE = 15;
	public static final int BREAK = 16;
	public static final int CONTINUE = 17;
	public static final int RETURN = 18;
	public static final int READ = 19;
	public static final int LPAREN = 20;
	public static final int RPAREN = 21;
	public static final int PRINT = 22;
	public static final int FOR = 23;
	public static final int INCREMENT = 24;
	public static final int DECREMENT = 25;
	public static final int AND = 26;
	public static final int OR = 27;
	public static final int MINUS = 28;
	public static final int NEW = 29;
	public static final int DOT = 30;
	public static final int EQUALTO = 31;
	public static final int NOTEQUALTO = 32;
	public static final int GREATER = 33;
	public static final int GREATEREQUAL = 34;
	public static final int LESS = 35;
	public static final int LESSEQUAL = 36;
	public static final int PLUS = 37;
	public static final int STAR = 38;
	public static final int SLASH = 39;
	public static final int PERCENT = 40;
	public static final int VOID = 41;
	public static final int THIS = 42;
	public static final int CLASS = 43;
	public static final int ARROW = 44;
	public static final int EXTENDS = 45;
	public static final int RANGE = 46;
	public static final int IN = 47;
	public static final int NUMCONST = 48;
	public static final int IDENT = 49;
	public static final int CHARCONST = 50;
	public static final int BOOLCONST = 51;
	
}

